export const pujas = [
  {
    id: 'mahakal-abhishek',
    name: 'Mahakal Abhishek',
    temple: 'Mahakaleshwar Temple, Ujjain',
    price: 1499,
    category: 'Health',
    tag: 'Most Popular',
    image: 'https://images.unsplash.com/photo-1621246025224-8b7052f574e8?auto=format&fit=crop&w=1200&q=80',
    description: 'Sacred Rudrabhishek and Sankalp performed with Panchamrit and Bilva Patra offerings.',
  },
  {
    id: 'kamakhya-devi-puja',
    name: 'Kamakhya Devi Puja',
    temple: 'Kamakhya Temple, Guwahati',
    price: 1899,
    category: 'Protection',
    tag: 'Shakti Peeth',
    image: 'https://images.unsplash.com/photo-1598091383021-15ddea10925d?auto=format&fit=crop&w=1200&q=80',
    description: 'Devi archana and sankalp for protection, prosperity, and removal of negative energy.',
  },
  {
    id: 'maha-rudrabhishek',
    name: 'Maha Rudrabhishek',
    temple: 'Kedarnath Temple, Uttarakhand',
    price: 1299,
    category: 'Peace',
    tag: 'Jyotirlinga',
    image: 'https://images.unsplash.com/photo-1626621331169-5f34be280ed9?auto=format&fit=crop&w=1200&q=80',
    description: 'Vedic Rudra puja with sankalp for peace, health, and spiritual strength.',
  },
  {
    id: 'kaal-sarp-dosh',
    name: 'Kaal Sarp Dosh Nivaran',
    temple: 'Trimbakeshwar Temple, Nashik',
    price: 2199,
    category: 'Dosha Nivaran',
    tag: 'Dosh Nivaran',
    image: 'https://images.unsplash.com/photo-1609947017136-9daf32a5eb16?auto=format&fit=crop&w=1200&q=80',
    description: 'Special ritual for dosha nivaran, career obstacles, and family peace.',
  },
];
